### ISSUE TITLE
框选 右键 拖动 快捷键 自动offset 紫条

### ISSUE THREAD

**Issue by ts8zs** [OpenCGSS/DereTore#35]
1. 框选
2. 右键给利用上啊 删除或者改方向之类的 弹个菜单也比在上面调好吧
3. 自动offset bpm 现在测timing无比蛋疼 最少我没找到试以外的方法 @statementreply
4. 紫条实现有问题吧...可能是因为我懒得编译的原因不是最新代码 看到issue了
5. 拖动
6. 键盘快捷键
7. 大概没了 最近有点忙 就不掺和了_(:3」∠)_

**Comment by hozuki** [comment]
（个人）计划在有时间的时候重写SD，现在基于WPF的方案在渲染效率和排版计算上很蛋疼。WPF的设计让框选没那么好做（做出来也不好看），SD的操作方式就……
键盘快捷键有，但是没标注出来（
slide的合法性判断现在仍然有问题，不过同样由于过去设计糟糕，代码一团乱。将来要改正。
测试现在一般先用BPMAnalyzer+Audition之类的工具做，然后输入再微调。我继续去摸索一下实现。
嘛总之这个版本等stat中，我先探路去。→\_→

**Comment by statementreply** [comment]
自动bpm/offset可以试试malody的，觉得可以的话我可以提供算法。主要缺少的功能是不支持多bpm，以及不能判定小节的起始拍是哪一拍，只知道每拍的位置。另外也有一些节拍探测算法的通病（有时会测出2倍或者0.5倍bpm这类问题）

**Comment by hozuki** [comment]
@statementreply 试了一下用能量法，精度稍糟糕（偏差在±3），起始时间未定（估计可以逆推但是麻烦，没写）

**Comment by hozuki** [comment]
好久之前的issue了……有一些功能在[新版](https://github.com/hozuki/StarlightDirector)里实现了，有些没有。不过制谱已经基本放弃了……
