### ISSUE TITLE
how to convert wav to hca encrypted with a custon key

### ISSUE THREAD

**Issue by Token713** [OpenCGSS/DereTore#51]
if a hca encrypted with a custon key，use vgmstream can decod,does it show that encode is feasible?
I know use hcaenc and hcacc could make that hca， but i don't konw  convert command ,
the game is Winning Eleven 2018 (Android) and custom key is  14121473,i use hcaenc make a general hca file,how to convert to encrypted hca with custom key,
hcacc.exe general.hca final.hca -ot 56 -i1 14121473???does it need -im -om options？
please help me!
test data link:https://www.lanzous.com/i3kce3c

**Comment by hozuki** [comment]
**For question 1:**

Yes. But be careful! vgmstream tries to decode HCA as plain text, or use known keys to decrypt it first, whichever works without error. So even if it outputs meaningful sound, that doesn't mean your file is correctly encrypted (e.g. the file can still be plain text). As far as I know, if you assign a decryption key to the official CRI HCA plugin, it decrypts all HCAs before decoding, ignoring its "cipher type" field. So the game would probably not accept plain text HCAs. To test whether the file is encrypted with the key you want, you must convert it back with exactly that key.

**For question 2:**

Please read the wiki more carefully. What is `-im` and `-om`?

hcacc automatically detects the cipher type of input file. So you don't need to provide the keys for decryption, unless the cipher type of *the input file* is 56. In your case the input file should be type 0 or type 1.
You should convert the key to its hexadecimal form and split it to two 8-hex-digit numbers. The calculator can do the job. 13121473=0x‭d77a01‬ so keys should be `00d77a01` and `00000000`.

Note: I should probably add an command line option to support using 16-hex-digit number directly to avoid the endianess mess. 🤔
