### ISSUE TITLE
WAV to HCA, Sound Is Not Working In Game

### ISSUE THREAD

**Issue by Lakoyo** [OpenCGSS/DereTore#52]
This is .hca music file I took it from pes 2019 android, (size 2mb) https://www.mediafire.com/file/5m69i8gx0685hda/sample.hca/file
When I try to convert .mp3 to .wav then to .hca file, the sound game become broken. 
Does the .hca file encrypted?
Please anyone can guide me step by step to successfully creating a working .hca file?

**Comment by hozuki** [comment]
In almost all games the HCA files are encrypted, so that resource hackers cannot easily extract their audio contents.
